### ISSUE TITLE
Anonyme checkout ?

### ISSUE THREAD

**Issue by crownbackend** [HelloAsso/checkout-sample#2]
Bonjour,

c'est possible de mettre une personne anonyme pour faire un don via le formulaire de paiement ? 

Cordialement,

English version : 

Hello,

Is it possible to put an anonymous person to make a donation via the payment form?

Sincerely,

**Comment by emnbdx** [comment]
Bonjour,

Non ce n'est pas possible il nous faut des informations pour processer le paiement.
