### ISSUE TITLE
Utiliser le sandbox

### ISSUE THREAD

**Issue by bcaro** [HelloAsso/checkout-sample#3]
# Issue Template

## Description

J'utilise le sanbox de helloasso : https://api.helloasso-sandbox.com/oauth2/token'); 
L'exemple n'est pas prévu pour.

## Steps to Reproduce

j'ai modifié les lignes ;
 C:\xampp\htdocs\sample\Services\HelloAssoApiWrapper.php (8 résultats)
	Ligne  22:             $request->setUrl('https://api.helloasso-sandbox.com/oauth2/token'); 
	Ligne  57:             $request->setUrl('https://api.helloasso-sandbox.com/v5/organizations/' . $this->config->organismSlug . '/checkout-intents'); 

## Expected Behavior

est-ce suffisant pour tester sur le sandbox ?

Le comportement obtenu avec cette modification est sans erreur mais l'appui sur le bouton payer recharge simplement la page.

J'ai testé l'api sandbox avec mon propre code de test et cela fonctionne.

**Comment by emnbdx** [comment]
Hello,

Il n'y a effectivement que l'API Wrapper qui communique avec l'api HelloAsso.
La modification est donc bonne.

Il faut bien penser à changer les clés pour mettre celle de sandbox.

Je viens de tester à nouveau pour être sur et je confirme que cela fonctionne bien
